### ISSUE TITLE
Cannot login to https://addons.thunderbird.net/ with SeaMonkey

### ISSUE THREAD

**Issue by petermad2** [thundernest/addons-server#145] opened 2020-08-11 18:51 UTC
### Describe the problem and steps to reproduce it:
I can no longer log in to https://addons.thunderbird.net/ when using SeaMonkey (2,53,3)

### What happened?
I am taken to https://accounts.firefox.com/authorization?action=signin&scope=profile&state=b5157fc4bcebc54893eac91a704c53c947885eb381cc9101e4d06f04f6217d82%3AL2RlL2RldmVsb3BlcnMvYWRkb24vcGluYmFsbC10aGVtZS92ZXJzaW9ucw&redirect_url=https%3A%2F%2Faddons.thunderbird.net%2Fapi%2Fv3%2Faccounts%2Fauthenticate%2F&client_id=25691f3bf98f8ea8
where the wating icon just keeps spinning.

### What did you expect to happen?
To log in to my account at https://addons.thunderbird.net/ to update my add-on https://addons.thunderbird.net/addon/pinball-theme/

### Anything else we should know?
SeaMonkeys Error console does not show any error.
I can log in with Firefox. Google Chrome, Opera, Microsoft Edge, but not with Internet Explorer or Safari for Windows.
It seems peculiar that I can not log in with the very same browser, that I want to update an add-on for.

**Comment by Sancus** [comment] 2020-08-11 19:23
Dupe of #143 - not likely to be fixed anytime soon I don't think, this is an upstream issue with Firefox Accounts.

**Closed by Sancus** 2020-08-11 19:23 UTC

**Comment by petermad2** [comment] 2020-08-11 20:02
I found a workaround - the problem with not being able to login occurs if Seamonkey is set to either "Identify as Firefox", or to "Identify as SeaMonky and advertise Firefox compatibility", but does not occur when set to "Identify as SeaMonkey" (under Advanced -> HTTP Networking).

In order to keep identifying as Firefox or advertise Firefox compatibility, I set this parameter in prefs.js:
**user_pref("general.useragent.override.firefox.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 SeaMonkey/2.53.3");**
to Identify af SeaMonkey at firefox.com
