### ISSUE TITLE
warnings on nonexisting functions at mailExtension upload

### ISSUE THREAD

**Issue by opto** [thundernest/addons-server#131] opened 2020-04-17 12:01 UTC
you want me to report that and keep track on that here?

what I definitely remember is MailTabs.setQuickFilter.
There was more, I can add that next time if you want. (mailTabs.getSelectedMessages )

The addon was accepted and is working in 68 and 76, so it is more a cosmetic issue.

Klaus

**Comment by Sancus** [comment] 2020-04-18 02:05
This is a dupe of https://github.com/thundernest/addons-server/issues/73

**Closed by Sancus** 2020-04-18 02:05 UTC
