### ISSUE TITLE
Plain thunderbird add-on links redirect to firefox add-ons store

### ISSUE THREAD

**Issue by mikehardy** [thundernest/addons-server#64] opened 2019-01-18 14:32 UTC
### Describe the problem and steps to reproduce it:
There appears to be an incorrect redirect for the plain (no query parameters) links to add-ons, that sends them to firefox add-ons store.

### What happened?

1. Go to main add-on site - https://addons.thunderbird.net/en-US/thunderbird/
1. Search for an add-on - note resulting links have query parameters - https://addons.thunderbird.net/en-US/thunderbird/search/?q=thunderlink&appver=&platform=
1. Click the link and it will work - https://addons.thunderbird.net/en-US/thunderbird/addon/thunderlink/?src=search

1. Take the query parameters off (note, these "plain" links are generated by the add-on site in certain places, specifically in the "view listing" section when you manage it, and in general a plain link should work?)
1. Click the plain link - https://addons.thunderbird.net/en-US/thunderbird/addon/thunderlink/

### What did you expect to happen?

Go to the add-on listing

Instead you go to the firefox add-on store where it 404s - https://addons.mozilla.org/en-US/firefox/addon/thunderlink/

### Anything else we should know?
Thanks for your time working with the thunderbird add-on ecosystem. For me, add-ons are differentiate it from a regular mail system.

**Comment by Sancus** [comment] 2019-01-18 22:54
This add-on contains a manifest.json, which means it gets Firefox compatibility by default currently until Thunderbird is manually added.

Because 302 redirects are very sticky in Firefox especially, if you go to the add-on link after changing the compatibility but without clearing your cache, it will use the cached redirect.

The plain add-on link in #5 works fine for me. So this is a dupe of https://github.com/thundernest/addons-server/pull/59

**Closed by Sancus** 2019-01-18 22:54 UTC

**Comment by mikehardy** [comment] 2019-01-18 23:45
Oh! Dang. Sorry for the dupe. I do add the TB compatibility manually so that scenario makes sense.
